
networks:
  proxy:
    external: true

services:
  portainer:
    privileged: true
    image: portainer/portainer-ee
    expose:
      - 9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /path/to/your/volume:/data # Bind mount a helyi fájlrendszer és a konténer között
    restart: always

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.rule=Host(`portainer.ivuserver.duckdns.org`)"
      - "traefik.http.routers.portainer.entrypoints=websecure"
      - "traefik.http.routers.portainer.tls=true"
      - "traefik.http.routers.portainer.tls.certresolver=production"
      - "traefik.http.routers.portainer.service=portainer-service@docker"
      - "traefik.http.services.portainer-service.loadbalancer.server.port=9000"

    networks:
      proxy:
        ipv4_address: 172.28.0.2
